spring.datasource:
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3307/jpa?serverTimezone=UTC&characterEncoding=UTF-8
#  username: root
#  password: 1234
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    generate-unique-name: false

spring.jpa:
  hibernate.ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
#  database-platform: org.hibernate.dialect.MySQL5Dialect
  #defer-datasource-initialization: true   #resource?? ?? ???? db??
#spring.sql.init.mode: always
server.servlet.encoding.force-response: true
spring:
  profiles:
    include: oauth
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always