spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3307/jpa?serverTimezone=UTC&characterEncoding=UTF-8
  username: root
  password: 1234

spring.jpa:
  hibernate.ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  database-platform: org.hibernate.dialect.MySQL5Dialect

server.servlet.encoding.force-response: true
spring:
  profiles:
    include: oauth
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
